# Enable C++ support
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libclang-3.8-dev
  - sudo ln -s /usr/lib/llvm-3.8/lib/clang/3.8/ /usr/lib/llvm-3.8/lib/clang/3.8.1
# Build steps
script:
  - ./build.sh
